name: tenkai-helm-ci CI

on: [push, pull_request]
      
jobs:
  build:
    runs-on: ubuntu-18.04
    env: 
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Lint
        run: make lint
      
      - name: Test
        run: make test
  
      - name: Build
        run: make build
      
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/build/tenkai-helm-api
  dockerize:
    needs: build
    runs-on: ubuntu-18.04
    env:
      IMAGE_REPO: softplan/tenkai-helm-api
    if: contains(github.ref, 'refs/heads/master') || contains(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: Dockerize
        run: |
          chmod +x build/tenkai-helm-api
          make container-image
          export TAG=${GITHUB_REF/refs\/heads\/}
          export TAG=${TAG/refs\/tags\/}
          docker tag ${{ env.IMAGE_REPO }} ${{ env.IMAGE_REPO }}:$TAG
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ env.IMAGE_REPO }}:$TAG